In [1]:
import pandas as pd

In [2]:
hmm=pd.read_csv('hm_147.csv')
hm=hmm.drop('BIS', axis=1)
hm.head()

hm_mode0  hm_mode1  hm_mode2  hm_mode3  hm_mode4
0  0.049831  0.520868  1.454838  1.784692  1.909118
1  0.049448  0.508191  1.455621  1.782323  1.904810
2  0.048924  0.507537  1.455589  1.782159  1.904986
3  0.047724  0.506852  1.454718  1.781959  1.904471
4  0.048067  0.507508  1.455498  1.781448  1.904483

In [3]:
hm_bis=hmm['BIS']

In [4]:
hcc=pd.read_csv('hc_147.csv')
hc=hcc.drop('BIS', axis=1)
hc.head()

hc_mode0  hc_mode1  hc_mode2  hc_mode3  hc_mode4
0  3.978740  1.216313  1.007100  1.004563  1.008659
1  3.996527  1.204408  1.007222  1.004806  1.009433
2  4.012654  1.203709  1.007256  1.004881  1.009488
3  4.204515  1.204209  1.007386  1.004657  1.009525
4  4.221884  1.203389  1.007200  1.004840  1.009517

In [5]:
per=pd.read_csv('perm_147.csv')
perm=per.drop('BIS', axis=1)
perm.head()

Perment_mode0  Perment_mode1  Perment_mode2  Perment_mode3  Perment_mode4
0       1.412010       1.917393       2.518968       2.576653       2.442158
1       1.414139       1.916961       2.518814       2.576485       2.442156
2       1.415896       1.916967       2.518801       2.576482       2.440540
3       1.411801       1.914910       2.518231       2.576213       2.441235
4       1.413689       1.916163       2.518594       2.576367       2.440560

In [6]:
pe=pd.read_csv('pet_147.csv')
pet=pe.drop('BIS', axis=1)
pet.head()

pet_mode0  pet_mode1  pet_mode2  pet_mode3  pet_mode4
0   1.002906   1.008682   1.021764   1.029176   1.034484
1   1.002925   1.008676   1.021758   1.029191   1.034484
2   1.002937   1.008676   1.021758   1.029207   1.034519
3   1.002900   1.008647   1.021731   1.029227   1.034504
4   1.002919   1.008665   1.021742   1.029202   1.034519

In [7]:
dis=pd.read_csv('disp_147.csv')
disp=dis.drop('BIS', axis=1)
disp.head()

Disp_mode0  Disp_mode1  Disp_mode2  Disp_mode3  Disp_mode4
0    1.151344    2.023257    2.026454    1.784954    2.020845
1    1.139086    2.023032    2.027358    1.789661    2.021334
2    1.160261    2.025580    2.032817    1.792239    2.023229
3    1.157799    2.023833    2.034414    1.798929    2.020622
4    1.154423    2.025165    2.031636    1.802524    2.019949

In [8]:
lzz=pd.read_csv('lzc_147.csv')
lzc=lzz.drop('BIS', axis=1)
lzc.head()

lzc_mode0  lzc_mode1  lzc_mode2  lzc_mode3  lzc_mode4
0       1403       1006        972        177         63
1       1458       1036        990        190         68
2       1468       1039        982        181         68
3       1468       1042        983        188         70
4       1446       1035        986        184         73

In [9]:
hf=pd.read_csv('hfd_147.csv')
hfd=hf.drop('BIS', axis=1)
hfd.head()

hfd_mode0  hfd_mode1  hfd_mode2  hfd_mode3  hfd_mode4
0   1.038787   1.529262   2.030527   2.029454   2.032978
1   1.040187   1.521417   2.028934   2.028740   2.033323
2   1.038775   1.521217   2.028689   2.028280   2.032565
3   1.041416   1.519013   2.030124   2.031429   2.033670
4   1.040177   1.521403   2.028500   2.028171   2.031715

In [10]:
spe=pd.read_csv('spec_147.csv')
spec=spe.drop('BIS', axis=1)
spec.head()

spec_mode0  spec_mode1  spec_mode2  spec_mode3  spec_mode4
0    6.063642    9.100702    8.519040    8.965288    8.525817
1    6.113495    9.048439    8.570311    8.988608    8.551958
2    5.842679    9.061026    8.582819    8.990811    8.540113
3    5.824327    9.058174    8.600857    8.979374    8.556002
4    5.719980    9.061481    8.587966    8.980800    8.549046

In [11]:
sv=pd.read_csv('svd_147.csv')
svd=sv.drop('BIS', axis=1)
svd.head()

svd_mode0  svd_mode1  svd_mode2  svd_mode3  svd_mode4
0   0.258617   1.078437   1.274077   1.273012   1.251937
1   0.256118   1.061768   1.276396   1.278469   1.264883
2   0.253154   1.060823   1.276656   1.278978   1.264926
3   0.249034   1.060287   1.277157   1.278185   1.265729
4   0.250773   1.061123   1.275609   1.278599   1.265863

In [12]:
dis=pd.read_csv('dispm_147.csv')
dispm=dis.drop('BIS', axis=1)
dispm.head()

dispm_mode0  dispm_mode1  dispm_mode2  dispm_mode3  dispm_mode4
0     0.990391     1.936638     1.969862     1.977817     1.924371
1     0.985747     1.936241     1.967646     1.978978     1.927041
2     0.996268     1.935342     1.967821     1.978710     1.927104
3     0.990203     1.935240     1.968915     1.978608     1.924654
4     0.987013     1.936824     1.967188     1.978336     1.924134

In [13]:
kf=pd.read_csv('kfd_147.csv')
kfd=kf.drop('BIS', axis=1)
kfd.head()

kfd_mode0  kfd_mode1  kfd_mode2  kfd_mode3  kfd_mode4
0   1.836333   2.426184   2.556330   2.660542   2.940791
1   1.686435   2.294578   2.577784   2.659485   2.933572
2   1.683617   2.291434   2.558690   2.639550   2.972046
3   1.762355   2.329471   2.589507   2.660636   2.932048
4   1.735479   2.312268   2.583872   2.698123   2.953145

In [14]:
det=pd.read_csv('detf_147.csv')
detf=det.drop('BIS', axis=1)
detf.head()

detf_mode0  detf_mode1  detf_mode2  detf_mode3  detf_mode4
0    1.482894    0.322259    0.017048    0.018654    0.031647
1    1.472012    0.286569    0.009611    0.013693    0.028887
2    1.467369    0.300093    0.014117    0.015930    0.030959
3    1.476168    0.318209    0.017277    0.017504    0.032561
4    1.499282    0.309967    0.015538    0.017586    0.031978

In [15]:
# concatenate the data

patient_147_data= pd.concat([hm, hc, kfd, detf, perm, pet, lzc, svd, hfd, spec, disp, dispm], axis=1)
patient_147_data['BIS']=hm_bis
patient_147_data

hm_mode0  hm_mode1  hm_mode2  hm_mode3  hm_mode4   hc_mode0  hc_mode1  \
0      0.049831  0.520868  1.454838  1.784692  1.909118   3.978740  1.216313   
1      0.049448  0.508191  1.455621  1.782323  1.904810   3.996527  1.204408   
2      0.048924  0.507537  1.455589  1.782159  1.904986   4.012654  1.203709   
3      0.047724  0.506852  1.454718  1.781959  1.904471   4.204515  1.204209   
4      0.048067  0.507508  1.455498  1.781448  1.904483   4.221884  1.203389   
...         ...       ...       ...       ...       ...        ...       ...   
22470  0.034715  0.615148  1.463017  1.794523  1.922291  11.182979  1.126941   
22471  0.033730  0.615179  1.463937  1.793265  1.922188  11.352195  1.126795   
22472  0.033640  0.616728  1.462406  1.793912  1.924751  11.275159  1.124045   
22473  0.033533  0.617242  1.461983  1.794181  1.925171  11.433262  1.121846   
22474  0.034003  0.614452  1.462513  1.796598  1.925030  11.228144  1.120930   

       hc_mode2  hc_mode3  hc_mode4  ...  Disp_mode1  Disp_mode2  Disp_mode3  \
0      1.007100  1.004563  1.008659  ...    2.023257    2.026454    1.784954   
1      1.007222  1.004806  1.009433  ...    2.023032    2.027358    1.789661   
2      1.007256  1.004881  1.009488  ...    2.025580    2.032817    1.792239   
3      1.007386  1.004657  1.009525  ...    2.023833    2.034414    1.798929   
4      1.007200  1.004840  1.009517  ...    2.025165    2.031636    1.802524   
...         ...       ...       ...  ...         ...         ...         ...   
22470  1.006622  1.004284  1.005522  ...    1.907695    2.055045    1.748292   
22471  1.006017  1.004012  1.005447  ...    1.910138    2.055251    1.751435   
22472  1.006614  1.004109  1.005235  ...    1.908218    2.056446    1.756032   
22473  1.006590  1.003995  1.005193  ...    1.903668    2.055773    1.759159   
22474  1.005618  1.004123  1.005143  ...    1.901570    2.056678    1.751567   

       Disp_mode4  dispm_mode0  dispm_mode1  dispm_mode2  dispm_mode3  \
0        2.020845     0.990391     1.936638     1.969862     1.977817   
1        2.021334     0.985747     1.936241     1.967646     1.978978   
2        2.023229     0.996268     1.935342     1.967821     1.978710   
3        2.020622     0.990203     1.935240     1.968915     1.978608   
4        2.019949     0.987013     1.936824     1.967188     1.978336   
...           ...          ...          ...          ...          ...   
22470    1.969070     0.898178     2.030383     1.966629     1.967833   
22471    1.967968     0.902689     2.031988     1.967498     1.969176   
22472    1.965923     0.906204     2.031437     1.965309     1.967801   
22473    1.963803     0.900508     2.032939     1.965968     1.968623   
22474    1.962926     0.907497     2.032999     1.966643     1.967541   

       dispm_mode4   BIS  
0         1.924371  96.7  
1         1.927041  86.6  
2         1.927104  76.5  
3         1.924654  76.5  
4         1.924134  73.3  
...            ...   ...  
22470     1.944206  89.4  
22471     1.945567  89.5  
22472     1.947828  87.7  
22473     1.945962  88.7  
22474     1.946790  89.5  

[22475 rows x 61 columns]

In [16]:
patient_147_data.to_csv('Patient 147_data.csv', index=False)

Original Data:
 [[10 20 30]
 [15 25 35]
 [ 5 10 15]]

Scaled Data:
 [[0.5        0.66666667 0.75      ]
 [1.         1.         1.        ]
 [0.         0.         0.        ]]
